alter table if exists paciente add constraint paciente_pk primary key (nro_paciente);
alter table if exists medique add constraint medique_pk primary key (dni_medique);
alter table if exists consultorio add constraint consultorio_pk primary key (nro_consultorio);
alter table if exists agenda add constraint agenda_pk primary key (dni_medique, dia);
alter table if exists turno add constraint turno_pk primary key (nro_turno);
alter table if exists reprogramacion add constraint reprogramacion_pk primary key (nro_turno);
alter table if exists error add constraint error_pk primary key (nro_error);
alter table if exists cobertura add constraint cobertura_pk primary key (dni_medique, nro_obra_social);
alter table if exists obra_social add constraint obra_social_pk primary key (nro_obra_social);
alter table if exists liquidacion_cabecera add constraint liquidacion_cabecera_pk primary key (nro_liquidacion);
alter table if exists liquidacion_detalle add constraint liquidacion_detalle_pk primary key (nro_liquidacion, nro_linea);
alter table if exists envio_email add constraint envio_email_pk primary key (nro_email);
