begin transaction;
alter table if exists paciente add constraint nro_obra_social_fk foreign key (nro_obra_social) references obra_social (nro_obra_social);
alter table if exists agenda add constraint dni_medique_fk foreign key (dni_medique) references medique (dni_medique);
alter table if exists agenda add constraint nro_consultorio_fk foreign key (nro_consultorio) references consultorio (nro_consultorio);
alter table if exists turno add constraint nro_consultorio_fk foreign key (nro_consultorio) references consultorio (nro_consultorio);
alter table if exists turno add constraint dni_medique_fk foreign key (dni_medique) references medique (dni_medique);
alter table if exists turno add constraint nro_paciente_fk foreign key (nro_paciente) references paciente (nro_paciente);
alter table if exists turno add constraint nro_obra_social_consulta_fk foreign key (nro_obra_social_consulta) references obra_social (nro_obra_social);
alter table if exists reprogramacion add constraint nro_turno_fk foreign key (nro_turno) references turno (nro_turno);
alter table if exists cobertura add constraint dni_medique_fk foreign key (dni_medique) references medique (dni_medique);
alter table if exists cobertura add constraint nro_obra_social_fk foreign key (nro_obra_social) references obra_social (nro_obra_social);
alter table if exists liquidacion_cabecera add constraint nro_obra_social_fk foreign key (nro_obra_social) references obra_social (nro_obra_social);
alter table if exists liquidacion_detalle add constraint nro_liquidacion_fk foreign key (nro_liquidacion) references liquidacion_cabecera (nro_liquidacion);
alter table if exists liquidacion_detalle add constraint dni_medique_fk foreign key (dni_medique) references medique (dni_medique);
commit;